#! /usr/bin/env sh

#
# src/tafo
#
# vim: set ft=sh:
#

SELF=`readlink $0`
N=`basename "$0"`

if test "$N" = "tafo"; then
  tail -f $1 | ruby -n $SELF.rb
elif test "$N" = "taca"; then
  cat $1 | ruby -n $SELF.rb
elif test "$N" = "tale"; then
  cat $1 | ruby -n $SELF.rb | less -R
else
  echo "what do you mean by \"$N\"?"
fi

